[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
hyper = { version = "1.5.2", features = ["full"] }
hyper-tls = "0.6.0"
hyper-util = { version = "0.1.10", features = ["client"] }
once_cell = "1.20.2"
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tower-livereload = "0.9.5"
web-push-native = { path = "../web_push" }
