[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.2"
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
hyper = { version = "1.1.0", features = ["full"] }
hyper-tls = "0.6.0"
hyper-util = { version = "0.1.2", features = ["client"] }
once_cell = "1.19.0"
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tower-livereload = "0.9.1"
web-push-native = { path = "../web_push" }
