[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
hyper = { version = "0.14.27", features = ["full"] }
hyper-rustls = "0.24.1"
once_cell = "1.18.0"
serde_json = "1.0.104"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tower-livereload = "0.8.0"
web-push-native = { path = "../web_push" }
